image: Visual Studio 2017
configuration: Release
platform: Any CPU

skip_commits:
  files:
    - '*.md'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{build}'
  informational_version: '{version}'
before_build:
- cmd: dotnet restore AspNetCore.TypeSafe.sln
build:
  verbosity: minimal
after_build:
- cmd: dotnet pack AspNetCore.TypeSafe.Core/AspNetCore.TypeSafe.Core.csproj
- cmd: dotnet pack AspNetCore.TypeSafe.Server/AspnetCore.TypeSafe.Server.csproj
- cmd: dotnet pack AspNetCore.TypeSafe.Client.RestSharp/AspnetCore.TypeSafe.Client.RestSharp.csproj
- cmd: dotnet pack AspNetCore.TypeSafe.Client.SignalR/AspnetCore.TypeSafe.Client.SignalR.csproj
artifacts:
- path: '**\*.nupkg'
deploy: off

for:
-
  branches:
    only:
      - dev

  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}-alpha'
    package_version: '{version}-alpha'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version} (pre-release)'